#if DEBUG
#include "vulkan_errors.h"
#include "log.h"
enum {
    SOL_VULKAN_SUCCESS = 0,
    SOL_VULKAN_NOT_READY = 1,
    SOL_VULKAN_TIMEOUT = 2,
    SOL_VULKAN_EVENT_SET = 3,
    SOL_VULKAN_EVENT_RESET = 4,
    SOL_VULKAN_INCOMPLETE = 5,
    SOL_VULKAN_ERROR_OUT_OF_HOST_MEMORY = -1,
    SOL_VULKAN_ERROR_OUT_OF_DEVICE_MEMORY = -2,
    SOL_VULKAN_ERROR_INITIALIZATION_FAILED = -3,
    SOL_VULKAN_ERROR_DEVICE_LOST = -4,
    SOL_VULKAN_ERROR_MEMORY_MAP_FAILED = -5,
    SOL_VULKAN_ERROR_LAYER_NOT_PRESENT = -6,
    SOL_VULKAN_ERROR_EXTENSION_NOT_PRESENT = -7,
    SOL_VULKAN_ERROR_FEATURE_NOT_PRESENT = -8,
    SOL_VULKAN_ERROR_INCOMPATIBLE_DRIVER = -9,
    SOL_VULKAN_ERROR_TOO_MANY_OBJECTS = -10,
    SOL_VULKAN_ERROR_FORMAT_NOT_SUPPORTED = -11,
    SOL_VULKAN_ERROR_FRAGMENTED_POOL = -12,
    SOL_VULKAN_ERROR_UNKNOWN = -13,
    SOL_VULKAN_ERROR_OUT_OF_POOL_MEMORY = -1000069000,
    SOL_VULKAN_ERROR_INVALID_EXTERNAL_HANDLE = -1000072003,
    SOL_VULKAN_ERROR_FRAGMENTATION = -1000161000,
    SOL_VULKAN_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS = -1000257000,
    SOL_VULKAN_PIPELINE_COMPILE_REQUIRED = 1000297000,
    SOL_VULKAN_ERROR_SURFACE_LOST_KHR = -1000000000,
    SOL_VULKAN_ERROR_NATIVE_WINDOW_IN_USE_KHR = -1000000001,
    SOL_VULKAN_SUBOPTIMAL_KHR = 1000001003,
    SOL_VULKAN_ERROR_OUT_OF_DATE_KHR = -1000001004,
    SOL_VULKAN_ERROR_INCOMPATIBLE_DISPLAY_KHR = -1000003001,
    SOL_VULKAN_ERROR_VALIDATION_FAILED_EXT = -1000011001,
    SOL_VULKAN_ERROR_INVALID_SHADER_NV = -1000012000,
    SOL_VULKAN_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR = -1000023000,
    SOL_VULKAN_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR = -1000023001,
    SOL_VULKAN_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR = -1000023002,
    SOL_VULKAN_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR = -1000023003,
    SOL_VULKAN_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR = -1000023004,
    SOL_VULKAN_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR = -1000023005,
    SOL_VULKAN_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT = -1000158000,
    SOL_VULKAN_ERROR_NOT_PERMITTED_KHR = -1000174001,
    SOL_VULKAN_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT = -1000255000,
    SOL_VULKAN_THREAD_IDLE_KHR = 1000268000,
    SOL_VULKAN_THREAD_DONE_KHR = 1000268001,
    SOL_VULKAN_OPERATION_DEFERRED_KHR = 1000268002,
    SOL_VULKAN_OPERATION_NOT_DEFERRED_KHR = 1000268003,
    SOL_VULKAN_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR = -1000299000,
    SOL_VULKAN_ERROR_COMPRESSION_EXHAUSTED_EXT = -1000338000,
    SOL_VULKAN_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT = 1000482000,
    SOL_VULKAN_ERROR_OUT_OF_POOL_MEMORY_KHR = SOL_VULKAN_ERROR_OUT_OF_POOL_MEMORY,
    SOL_VULKAN_ERROR_INVALID_EXTERNAL_HANDLE_KHR = SOL_VULKAN_ERROR_INVALID_EXTERNAL_HANDLE,
    SOL_VULKAN_ERROR_FRAGMENTATION_EXT = SOL_VULKAN_ERROR_FRAGMENTATION,
    SOL_VULKAN_ERROR_NOT_PERMITTED_EXT = SOL_VULKAN_ERROR_NOT_PERMITTED_KHR,
    SOL_VULKAN_ERROR_INVALID_DEVICE_ADDRESS_EXT = SOL_VULKAN_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS,
    SOL_VULKAN_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR = SOL_VULKAN_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS,
    SOL_VULKAN_PIPELINE_COMPILE_REQUIRED_EXT = SOL_VULKAN_PIPELINE_COMPILE_REQUIRED,
    SOL_VULKAN_ERROR_PIPELINE_COMPILE_REQUIRED_EXT = SOL_VULKAN_PIPELINE_COMPILE_REQUIRED,
};

const char *match_vk_error(int error) {
    switch (error) {
    case SOL_VULKAN_SUCCESS:
        return "VK_SUCCESS";
    case SOL_VULKAN_NOT_READY:
        return "VK_NOT_READY";
    case SOL_VULKAN_TIMEOUT:
        return "VK_TIMEOUT";
    case SOL_VULKAN_EVENT_SET:
        return "VK_EVENT_SET";
    case SOL_VULKAN_EVENT_RESET:
        return "VK_EVENT_RESET";
    case SOL_VULKAN_INCOMPLETE:
        return "VK_INCOMPLETE";
    case SOL_VULKAN_ERROR_OUT_OF_HOST_MEMORY:
        return "VK_ERROR_OUT_OF_HOST_MEMORY";
    case SOL_VULKAN_ERROR_OUT_OF_DEVICE_MEMORY:
        return "VK_ERROR_OUT_OF_DEVICE_MEMORY";
    case SOL_VULKAN_ERROR_INITIALIZATION_FAILED:
        return "VK_ERROR_INITIALIZATION_FAILED";
    case SOL_VULKAN_ERROR_DEVICE_LOST:
        return "VK_ERROR_DEVICE_LOST";
    case SOL_VULKAN_ERROR_MEMORY_MAP_FAILED:
        return "VK_ERROR_MEMORY_MAP_FAILED";
    case SOL_VULKAN_ERROR_LAYER_NOT_PRESENT:
        return "VK_ERROR_LAYER_NOT_PRESENT";
    case SOL_VULKAN_ERROR_EXTENSION_NOT_PRESENT:
        return "VK_ERROR_EXTENSION_NOT_PRESENT";
    case SOL_VULKAN_ERROR_FEATURE_NOT_PRESENT:
        return "VK_ERROR_FEATURE_NOT_PRESENT";
    case SOL_VULKAN_ERROR_INCOMPATIBLE_DRIVER:
        return "VK_ERROR_INCOMPATIBLE_DRIVER";
    case SOL_VULKAN_ERROR_TOO_MANY_OBJECTS:
        return "VK_ERROR_TOO_MANY_OBJECTS";
    case SOL_VULKAN_ERROR_FORMAT_NOT_SUPPORTED:
        return "VK_ERROR_FORMAT_NOT_SUPPORTED";
    case SOL_VULKAN_ERROR_FRAGMENTED_POOL:
        return "VK_ERROR_FRAGMENTED_POOL";
    case SOL_VULKAN_ERROR_UNKNOWN:
        return "VK_ERROR_UNKNOWN";
    case SOL_VULKAN_ERROR_OUT_OF_POOL_MEMORY:
        return "VK_ERROR_OUT_OF_POOL_MEMORY";
    case SOL_VULKAN_ERROR_INVALID_EXTERNAL_HANDLE:
        return "VK_ERROR_INVALID_EXTERNAL_HANDLE";
    case SOL_VULKAN_ERROR_FRAGMENTATION:
        return "VK_ERROR_FRAGMENTATION";
    case SOL_VULKAN_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS:
        return "VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS";
    case SOL_VULKAN_PIPELINE_COMPILE_REQUIRED:
        return "VK_PIPELINE_COMPILE_REQUIRED";
    case SOL_VULKAN_ERROR_SURFACE_LOST_KHR:
        return "VK_ERROR_SURFACE_LOST_KHR";
    case SOL_VULKAN_ERROR_NATIVE_WINDOW_IN_USE_KHR:
        return "VK_ERROR_NATIVE_WINDOW_IN_USE_KHR";
    case SOL_VULKAN_SUBOPTIMAL_KHR:
        return "VK_SUBOPTIMAL_KHR";
    case SOL_VULKAN_ERROR_OUT_OF_DATE_KHR:
        return "VK_ERROR_OUT_OF_DATE_KHR";
    case SOL_VULKAN_ERROR_INCOMPATIBLE_DISPLAY_KHR:
        return "VK_ERROR_INCOMPATIBLE_DISPLAY_KHR";
    case SOL_VULKAN_ERROR_VALIDATION_FAILED_EXT:
        return "VK_ERROR_VALIDATION_FAILED_EXT";
    case SOL_VULKAN_ERROR_INVALID_SHADER_NV:
        return "VK_ERROR_INVALID_SHADER_NV";
    case SOL_VULKAN_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR:
        return "VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR";
    case SOL_VULKAN_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR";
    case SOL_VULKAN_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR";
    case SOL_VULKAN_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR";
    case SOL_VULKAN_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR";
    case SOL_VULKAN_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR:
        return "VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR";
    case SOL_VULKAN_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT:
        return "VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT";
    case SOL_VULKAN_ERROR_NOT_PERMITTED_KHR:
        return "VK_ERROR_NOT_PERMITTED_KHR";
    case SOL_VULKAN_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT:
        return "VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT";
    case SOL_VULKAN_THREAD_IDLE_KHR:
        return "VK_THREAD_IDLE_KHR";
    case SOL_VULKAN_THREAD_DONE_KHR:
        return "VK_THREAD_DONE_KHR";
    case SOL_VULKAN_OPERATION_DEFERRED_KHR:
        return "VK_OPERATION_DEFERRED_KHR";
    case SOL_VULKAN_OPERATION_NOT_DEFERRED_KHR:
        return "VK_OPERATION_NOT_DEFERRED_KHR";
    case SOL_VULKAN_ERROR_COMPRESSION_EXHAUSTED_EXT:
        return "VK_ERROR_COMPRESSION_EXHAUSTED_EXT";
    case SOL_VULKAN_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT:
        return "VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT";
    default:
        log_print_error("UNKOWN VULKAN ERROR CODE");
        return NULL;
    }
}
#endif // if DEBUG
